### ISSUE TITLE
Support version-less manifests

### ISSUE THREAD

**Issue by faern** [Henning-K/cargo-authors#10]
Since Rust 1.75.0 the [`version` field is optional](https://github.com/rust-lang/cargo/pull/12786). I have a crate without version. But when running `cargo author` I get:
```
error: failed to load manifest for workspace member `/foo`
caused by: failed to load manifest for workspace member `/foo`
caused by: failed to parse manifest at `/foo/Cargo.toml`
caused by: missing field `version`
in `package`
```
I guess this crate must upgrade its version on `cargo` for it to work?

**Comment by Henning-K** [comment]
Thanks for the heads-up on this change.

From what I could find in the linked pull request, the version field is now optional, but becomes required when you want to publish the crate.

It will be fixed in the next point release along with a crash¹ I found while testing changes for this issue (and some refactoring).

¹: no authors field in the package field AND no dependencies
